### ISSUE TITLE
Does not close after sim exit

### ISSUE THREAD

**Issue by vikingnope** [Fragtality/WorkingTitle2GSX#1]
I have an issue with this mod, where it does not close automatically after I exit the sim. I have to go to Task Manager and quit the application. I have auto-start with FSUIPC.

Let me know if you need anything in terms of troubleshooting this issue.

**Comment by Fragtality** [comment]
But you give it some Time to actually close itself? So it would be still open after let's say 5 Minutes?

What FSUIPC Version are you running? What das the RunIf Line with WorkingTitle2GSX.exe looks like in your FSUIPC7.ini File? (In the Directory you've installed FSUIPC to)

You could post a Log of WorkingTitle2GSX where it happens. (%appdata%\WorkingTitle2GSX\log)

**Comment by vikingnope** [comment]
Yes usually it stays open and I have to close it from task manager myself.

My FSUIPC version is 7.4.4

[WorkingTitle2GSX20240124.log](https://github.com/Fragtality/WorkingTitle2GSX/files/14038776/WorkingTitle2GSX20240124.log)

FSUIPC auto launch line:
```
[Programs]
RunIf1=CONNECTED,CLOSE,C:\Users\aidsc\AppData\Roaming\WorkingTitle2GSX\bin\WorkingTitle2GSX.exe
```

**Comment by Fragtality** [comment]
Hmm, going by the Log Messages it seems Flight Simulator itself is still detected as running - else WT2GSX would close itself.

Maybe as a Workaround it would help when you use KILL instead of CLOSE? That can have the Side-Effect that the Icon is still visible in the Systray (because the Binary is killed and can't clean that up).

```
[Programs]
RunIf1=CONNECTED,KILL,C:\Users\aidsc\AppData\Roaming\WorkingTitle2GSX\bin\WorkingTitle2GSX.exe
```

**Comment by vikingnope** [comment]
Changing it from CLOSE to KILL solved the issue for me, thanks a lot.
