### ISSUE TITLE
App hanging / not exiting after MSFS Shutdown

### ISSUE THREAD

**Issue by DavidEGTE** [Fragtality/WorkingTitle2GSX#2]
W2GSX is still on systray when exiting MSFS

**Comment by Fragtality** [comment]
... Logs?

**Comment by DavidEGTE** [comment]
[WorkingTitle2GSX20240218.log](https://github.com/Fragtality/WorkingTitle2GSX/files/14349027/WorkingTitle2GSX20240218.log)
[WorkingTitle2GSX20240219.log](https://github.com/Fragtality/WorkingTitle2GSX/files/14349028/WorkingTitle2GSX20240219.log)
[WorkingTitle2GSX20240220.log](https://github.com/Fragtality/WorkingTitle2GSX/files/14349029/WorkingTitle2GSX20240220.log)

Just checked the logs and there is nothing wrong, but lately on the last 2 sessions the systray for W2GSX was active

**Comment by DavidEGTE** [comment]
I will keep a eye on it but, closing issue

**Comment by DavidEGTE** [comment]
Reopening as I just completed a session, MSFS closed normally
[WorkingTitle2GSX20240220.log](https://github.com/Fragtality/WorkingTitle2GSX/files/14352000/WorkingTitle2GSX20240220.log)
![image](https://github.com/Fragtality/WorkingTitle2GSX/assets/19428125/f114cb8d-356f-4c84-b940-08fac860521e)

**Comment by Fragtality** [comment]
Yeah the Icons sometimes become "stale" - but MSFS and WT2GSX should be closed (not running anymore). If you move/hover above the Icon it should disappear.

**Comment by DavidEGTE** [comment]
I know about the stale situation but even with the mouse passing over it , its annoying being there
