### ISSUE TITLE
Installer Dosent Work 

### ISSUE THREAD

**Issue by cantresist** [Fragtality/WorkingTitle2GSX#3]
When i opened the installer for the first time, it prompted me saying that i needed to download download .net runtime, i did, tried opening the installer again. Nothing pops up. What do i do?

**Comment by Fragtality** [comment]
Sorry I cant follow - the Installer does not say something like that. It is supposed to download and install the .NET Runtime automatically.

Maybe a Screenshot of the Prompt you mean would help?

**Comment by cantresist** [comment]
It did install it, like i pressed "download it", then nothing happened. Nothing popped up after that at all, i tried opening it again but still nothing happened

**Comment by Fragtality** [comment]
Sorry, but it still does not make any Sense to me - I don't know what you are talking about.
There is no "download it" Button that you could have pressed.

Like already requested, a Screenshot of what you referring to could help.

**Comment by cantresist** [comment]
I go to workingtitle2gsx>Installer>AppPackage> and double click the workingtitle2gsx.exe. After that nothing happens. Did I install it incorrectly or something like that?

**Comment by Fragtality** [comment]
You go to what ❓

**Comment by Fragtality** [comment]
Waaaaaaaaaaiiiit ... what *exactly* have you downloaded?
Could it be that did not even read the 4th Line of the Readme?!
![image](https://github.com/Fragtality/WorkingTitle2GSX/assets/78614902/5c4443b6-af30-437d-91ba-55d1a8855d7b)

**Comment by cantresist** [comment]
oh um..... My bad gang. (Really sorry, i thought it was for Pilots Deck/Stream Deck).
Thanks for telling me!

**Comment by Fragtality** [comment]
Well, it is basically the same for PilotsDeck: the latest installer for the official release Version is found under a Releases (and .NET will be installed automatically also).

If you where looking for the WorkingTitle 787 Profile for PilotsDeck: that is on flightsim.to.
This Tool "only" handles basic Fuel- & Payload-Synchronization with GSX.
